---

- name: Check if zprezto on disk
  stat:
    path: ~/.zprezto
  always_run: yes
  changed_when: false
  register: zprezto_dir

- name: Clone Prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ~/.zprezto
  when: zprezto_dir.stat.exists == false

- name: Copy .zpreztorc
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: 0644
  with_items:
    - .zpreztorc
    - .zprofile
    - .zshrc

- name: Enable brew zsh binary
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/zsh
    state: present
  become: true

- name: Set shell to zsh
  shell: "chsh -s /bin/zsh"
  when: "'/usr/local/bin/zsh' != ansible_env.SHELL"
