---

- name: Install homebrew essentials
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - gpg
    - jq
    - openssl
    - mercurial #gvm wants this
    - nvm
    - ssh-copy-id
    - tree
    - watch
    - wget
    - zsh
